# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='cuisines.Cuisine'),
        ),
    ]
