# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wines', '0004_wine_grapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.Wine')),
            ],
        ),
    ]
