# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ['name']},
        ),
    ]
