# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vintage', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('fruit', models.PositiveIntegerField(default=0)),
                ('sweetness', models.PositiveIntegerField(default=0)),
                ('tannin', models.PositiveIntegerField(default=0)),
                ('body', models.PositiveIntegerField(default=0)),
                ('acidity', models.PositiveIntegerField(default=0)),
                ('alcohol', models.PositiveIntegerField(default=0)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.Style')),
            ],
        ),
    ]
