# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
