# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0002_auto_20170823_2342'),
        ('wines', '0003_auto_20170823_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='grapes',
            field=models.ManyToManyField(to='grapes.Grape'),
        ),
    ]
