# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_wine_grapes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['style', 'name']},
        ),
        migrations.AddField(
            model_name='wine',
            name='label',
            field=models.CharField(default='', max_length=10),
        ),
    ]
