# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20170823_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='label',
        ),
        migrations.AlterField(
            model_name='wine',
            name='fruit',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sweetness',
            field=models.PositiveIntegerField(choices=[(1, 'Bone-Dry'), (2, 'Dry'), (3, 'Off-Dry'), (4, 'Sweet'), (5, 'Very Sweet')], default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='tannin',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Average'), (4, 'Astringent'), (5, 'Very Astringent')], default=0),
        ),
    ]
