# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_auto_20170824_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='vintage',
        ),
    ]
