# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0008_remove_wine_vintage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
