# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grape',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
