CREATE TABLE booze (
  product_id INTEGER NOT NULL,
  added_on TIMESTAMPTZ NOT NULL,
  name VARCHAR(255) NOT NULL,
  origin VARCHAR(255) NOT NULL,
  price numeric(12,2) NOT NULL,
  regular_price numeric(12,2) NOT NULL,
  primary_category character varying(255) NOT NULL,
  secondary_category character varying(255) NOT NULL,
  tertiary_category character varying(255) NOT NULL,
  style character varying(255) NOT NULL,
  unit_volume integer NOT NULL,
  varietal character varying(255) NOT NULL,
  alcohol integer NOT NULL,
  sugar character varying(255) NOT NULL,
  sugar_in_grams integer NOT NULL,
  producer character varying(255) NOT NULL,
  stock_type character varying(100) NOT NULL,
  tasting_notes text NOT NULL,
  is_seasonal boolean NOT NULL,
  is_vqa boolean NOT NULL,
  is_ocb boolean NOT NULL,
  has_limited_time_offer boolean NOT NULL,
  has_value_added_promotion boolean NOT NULL,
  inventory integer NOT NULL,
  inventory_price numeric(12,2) NOT NULL,
  inventory_volume integer NOT NULL,
  limited_time_offer_ends character varying(255) NOT NULL,
  limited_time_offer_savings numeric(12,2) NOT NULL,
  released_on character varying(255) NOT NULL,
  total_package_units smallint NOT NULL,
  volume integer NOT NULL,
  UNIQUE (added_on, product_id)
);


