# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primary_category', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_category', models.CharField(blank=True, default='', max_length=255)),
                ('tertiary_category', models.CharField(blank=True, default='', max_length=255)),
                ('style', models.CharField(blank=True, default='', max_length=255)),
                ('unit_volume', models.PositiveIntegerField()),
                ('varietal', models.CharField(blank=True, default='', max_length=255)),
                ('alcohol', models.PositiveIntegerField(default=0)),
                ('sugar', models.CharField(blank=True, default='', max_length=255)),
                ('sugar_in_grams', models.PositiveIntegerField(default=0)),
                ('producer', models.CharField(blank=True, default='', max_length=255)),
                ('stock_type', models.CharField(blank=True, default='', max_length=100)),
                ('tasting_notes', models.CharField(blank=True, default='', max_length=255)),
                ('serving_suggestion', models.TextField(blank=True, default='')),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_vqa', models.BooleanField(default=False)),
                ('is_ocb', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('image_thumb_url', models.CharField(blank=True, default='', max_length=255)),
                ('has_limited_time_offer', models.BooleanField(default=False)),
                ('has_value_added_promotion', models.BooleanField(default=False)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('inventory_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_volume', models.PositiveIntegerField(default=0)),
                ('limited_time_offer_ends', models.CharField(blank=True, default='', max_length=255)),
                ('limited_time_offer_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('released_on', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('total_package_units', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
