# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tasting_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
