# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170921_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
