# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170921_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limited_time_offer_savings',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='savings'),
        ),
    ]
